$(GENERATED_FILES_DIR)/compiler-builtins-Makefile: $(GENERATED_FILES_DIR_STAMP) $(TOOLS_DIR)/generate-makefile lib/compiler-builtins/build.config
	$(TOOLS_DIR)/generate-makefile lib/compiler-builtins/build.config $@

include $(GENERATED_FILES_DIR)/compiler-builtins-Makefile
